wandb_version: 1

learning_rage:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.9
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700144303.909665
    t:
      1:
      - 1
      - 5
      - 11
      - 40
      - 41
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 40
      - 41
      - 49
      - 51
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.15.9
      6: 4.29.2
      8:
      - 1
      - 3
      - 5
